server:
  shutdown: graceful

spring:
  profiles:
    include:
      - db

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-time: 3600000 # 60*60*1000 = 1시간
  refresh-token-expiration-time: 604800000 # 7*24*60*60*1000 = 7일
  registration-token-expiration-time: 1000