server:
  shutdown: graceful
  port: 8080
  ssl:
    key-store: classpath:/ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}

spring:
  profiles:
    include:
      - db
      - jwt
