[[Job-Description-API]]
== Job-Description-API

[[CREATE-JD]]
=== JD 등록

operation::JobDescriptionControllerTest/createJobDescription[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[CREATE-JD-EXCEPTION]]
==== JD 등록 시 예외 (빈 값, 또는 NULL이 들어올 경우)

operation::JobDescriptionControllerTest/createJobDescriptionWithEmptyValue[snippets='http-request,request-headers,http-response']

[[CREATE-JD-EXCEPTION-2]]
==== JD 등록 시 예외 (시작일이 종료일보다 늦을 경우)

operation::JobDescriptionControllerTest/createJobDescriptionWithInvalidDate[snippets='http-request,request-headers,http-response']

[[CREATE-APPLY]]
=== JD 자소서 등록

operation::JobDescriptionControllerTest/createApply[snippets='http-request,path-parameters,request-headers,request-fields,http-response']

[[CREATE-APPLY-EXCEPTION-1]]
==== JD 자소서 등록 시 예외 (내용이 비어있는 경우)

operation::JobDescriptionControllerTest/createApplyWithEmptyContent[snippets='http-request,path-parameters,request-headers,http-response']

[[GET-JD-LIST]]
=== JD 목록 조회

operation::JobDescriptionControllerTest/getJobDescription[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

[[GET-JD-DETAIL]]
=== JD 상세 조회

operation::JobDescriptionControllerTest/getJobDescriptionDetail[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[GET-APPLY-INFO]]
=== 자기소개서 조회

operation::JobDescriptionControllerTest/getApplyInfo[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[UPDATE-APPLY]]
=== 자기소개서 수정

operation::JobDescriptionControllerTest/updateApplyInfo[snippets='http-request,path-parameters,request-headers,request-fields,http-response']

[[UPDATE-WRITE-STATUS]]
=== JD 작성 상태 수정

operation::JobDescriptionControllerTest/updateWriteStatus[snippets='http-request,path-parameters,request-headers,http-response']

[[UPDATE-JD]]
=== JD 수정

operation::JobDescriptionControllerTest/updateJobDescription[snippets='http-request,path-parameters,request-headers,request-fields,http-response']

[[DELETE-JD]]
=== JD 삭제

operation::JobDescriptionControllerTest/deleteJobDescription[snippets='http-request,path-parameters,request-headers,http-response']








