[[Tag-API]]
== Tag-API

[[CreateParentTagTest]]
=== 상위 태그 등록 API

operation::TagControllerTest/createParentTagTest/[snippets='http-request,request-fields,http-response,response-fields']

[[CreateChildTagTest]]
=== 하위 태그 등록 API

operation::TagControllerTest/createChildTagTest/[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[GetParentTagTest]]
=== 상위 태그 조회 API

operation::TagControllerTest/getAllParentTagByUserTest/[snippets='http-request,request-headers,http-response,response-fields']

[[GetTopRankTagTest]]
=== 연도 내 경험 최근 추가 순 태그 조회 API

operation::TagControllerTest/getTopRankParentTagTest/[snippets='http-request,request-headers,http-response,response-fields']

[[GetParentTagsByFilter]]
=== 연도 내 상위 태그 조회 API

operation::TagControllerTest/getParentTagsByFilter/[snippets='http-request,http-response,response-fields']

[[GetChildTagTest]]
=== 하위 태그 전체 조회 API

operation::TagControllerTest/getAllChildTagTest/[snippets='http-request,path-parameters,http-response,response-fields']

[[GetChildTagsByFilter]]
=== 상위 태그 내 하위 태그 조회 API

operation::TagControllerTest/getChildTagsByYear/[snippets='http-request,path-parameters,http-response,response-fields']

[[duplicatedParentTagTest]]
==== 상위 태그 이름 중복 예외

operation::TagControllerTest/duplicatedParentTagTest/[snippets='http-request,request-fields,http-response,response-fields']

[[duplicatedChildTagTest]]
==== 하위 태그 이름 중복 예외

operation::TagControllerTest/duplicatedChildTagTest/[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[overTagCountLimitTest]]
==== 태그 개수 제한 이상 등록 요청 예외

operation::TagControllerTest/overTagCountLimitTest/[snippets='http-request,path-parameters,request-fields,http-response,response-fields']
