jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  registration-token-expiration-time: ${JWT_REGISTRATION_TOKEN_EXPIRATION_TIME}